kind: pipeline
type: docker
name: docker-melior-transformers

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

steps:
- name: install_and_run
  # image: python:${PYTHON_VERSION}-slim
  # image: ubuntu:bionic
  image: python:3.6-slim
  pull: if-not-exists
  commands:
    # Install all libs in the docker
    - |
      apt-get update -qq && \
      apt-get install -y --no-install-recommends \
      build-essential \
      sudo \
      wget \
      unzip \
      openssh-client \
      graphviz-dev \
      pkg-config \
      git-core \
      openssl \
      libssl-dev \
      libffi6 \
      libffi-dev \
      libpng-dev \
      libpq-dev \
      curl && \
      apt-get clean && \
      rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    # Install MAI dependencies
    - python -m pip install -U pip==19.3.1
    - make install
    # job: Code Formatting
    - make lint
    # job: Type Check
    # - make types
    # Test
    - make test

