# See more options at https://digitalocean-runner.docs.drone.io/configuration/overview/

kind: pipeline
name: digitalocean-melior-transformers
type: digitalocean

token:
  # organization secret set by terraform
  from_secret: digital_ocean_token

# digital ocean droplet configuration
server:
  image: 55827312
  size: m-16gb
  region: lon1

steps:
  - name: install
    commands:
      - make install

  - name: lint
    commands:
      - make lint

  # - name: types
  #   commands:
  #     - make types

  - name: test
    commands:
      - make test